use_frameworks!

target 'Snap2me_Example' do
  pod 'Snap2me', :path => '../'

  target 'Snap2me_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
